name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        chmod +x ./tests/*.sh
        ./tests/test_install.sh
        ./tests/test_switch.sh
        ./tests/test_package.sh
